// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/models.dart';
import 'api/simple.dart';
import 'api/ssh.dart';
import 'api/vault.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -2017828654;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_remote_manager',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSshSshConnectionConnect({
    required SshConnection that,
    required Connection connection,
  });

  Future<void> crateApiSshSshConnectionDisconnect({
    required SshConnection that,
  });

  Future<String> crateApiSshSshConnectionExecuteCommand({
    required SshConnection that,
    required String command,
  });

  Future<SshConnection> crateApiSshSshConnectionNew();

  Future<String> crateApiSshSshConnectionTestConnection({
    required SshConnection that,
  });

  Future<void> crateApiVaultVaultAddConnection({
    required Vault that,
    required Connection connection,
  });

  Future<void> crateApiVaultVaultCreate({
    required Vault that,
    required String masterPassword,
  });

  Future<void> crateApiVaultVaultDeleteConnection({
    required Vault that,
    required String id,
  });

  Future<Connection> crateApiVaultVaultGetConnection({
    required Vault that,
    required String id,
  });

  Future<List<Connection>> crateApiVaultVaultGetConnections({
    required Vault that,
  });

  Future<bool> crateApiVaultVaultIsUnlocked({required Vault that});

  Future<void> crateApiVaultVaultLoadFromFile({
    required Vault that,
    required String path,
    required String masterPassword,
  });

  Future<void> crateApiVaultVaultLock({required Vault that});

  Future<Vault> crateApiVaultVaultNew();

  Future<void> crateApiVaultVaultSaveToFile({
    required Vault that,
    required String path,
  });

  Future<void> crateApiVaultVaultUpdateConnection({
    required Vault that,
    required Connection connection,
  });

  Future<Connection> crateApiAppAddConnection({
    required String name,
    required Protocol protocol,
    required String host,
    required int port,
    String? username,
    String? password,
    String? privateKeyPath,
    required String path,
  });

  Future<Connection> crateApiModelsConnectionNew({
    required String name,
    required Protocol protocol,
    required String host,
    required int port,
  });

  Future<void> crateApiAppCreateVault({
    required String masterPassword,
    required String path,
  });

  String crateApiAppDefaultVaultPath();

  Future<void> crateApiAppDeleteConnection({
    required String id,
    required String path,
  });

  Future<List<Connection>> crateApiAppGetConnections();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  bool crateApiAppIsVaultUnlocked();

  void crateApiAppLockVault();

  Future<String> crateApiAppTestConnection({required String connectionId});

  Future<String> crateApiSshTestSshConnection({
    required String host,
    required int port,
    required String username,
    String? password,
    String? privateKeyPath,
  });

  Future<void> crateApiAppUnlockVault({
    required String masterPassword,
    required String path,
  });

  Future<void> crateApiAppUpdateConnection({
    required Connection connection,
    required String path,
  });

  bool crateApiAppVaultExists({required String path});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SshConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SshConnection;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SshConnectionPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Vault;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Vault;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VaultPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSshSshConnectionConnect({
    required SshConnection that,
    required Connection connection,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
            that,
            serializer,
          );
          sse_encode_box_autoadd_connection(connection, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshSshConnectionConnectConstMeta,
        argValues: [that, connection],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshConnectionConnectConstMeta =>
      const TaskConstMeta(
        debugName: "SshConnection_connect",
        argNames: ["that", "connection"],
      );

  @override
  Future<void> crateApiSshSshConnectionDisconnect({
    required SshConnection that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshSshConnectionDisconnectConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshConnectionDisconnectConstMeta =>
      const TaskConstMeta(
        debugName: "SshConnection_disconnect",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiSshSshConnectionExecuteCommand({
    required SshConnection that,
    required String command,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
            that,
            serializer,
          );
          sse_encode_String(command, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshSshConnectionExecuteCommandConstMeta,
        argValues: [that, command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshConnectionExecuteCommandConstMeta =>
      const TaskConstMeta(
        debugName: "SshConnection_execute_command",
        argNames: ["that", "command"],
      );

  @override
  Future<SshConnection> crateApiSshSshConnectionNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSshSshConnectionNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshConnectionNewConstMeta =>
      const TaskConstMeta(debugName: "SshConnection_new", argNames: []);

  @override
  Future<String> crateApiSshSshConnectionTestConnection({
    required SshConnection that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshSshConnectionTestConnectionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshConnectionTestConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "SshConnection_test_connection",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiVaultVaultAddConnection({
    required Vault that,
    required Connection connection,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
            that,
            serializer,
          );
          sse_encode_box_autoadd_connection(connection, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultVaultAddConnectionConstMeta,
        argValues: [that, connection],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultAddConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "Vault_add_connection",
        argNames: ["that", "connection"],
      );

  @override
  Future<void> crateApiVaultVaultCreate({
    required Vault that,
    required String masterPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
            that,
            serializer,
          );
          sse_encode_String(masterPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultVaultCreateConstMeta,
        argValues: [that, masterPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultCreateConstMeta => const TaskConstMeta(
    debugName: "Vault_create",
    argNames: ["that", "masterPassword"],
  );

  @override
  Future<void> crateApiVaultVaultDeleteConnection({
    required Vault that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultVaultDeleteConnectionConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultDeleteConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "Vault_delete_connection",
        argNames: ["that", "id"],
      );

  @override
  Future<Connection> crateApiVaultVaultGetConnection({
    required Vault that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultVaultGetConnectionConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultGetConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "Vault_get_connection",
        argNames: ["that", "id"],
      );

  @override
  Future<List<Connection>> crateApiVaultVaultGetConnections({
    required Vault that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_connection,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultVaultGetConnectionsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultGetConnectionsConstMeta =>
      const TaskConstMeta(
        debugName: "Vault_get_connections",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiVaultVaultIsUnlocked({required Vault that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultIsUnlockedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultIsUnlockedConstMeta =>
      const TaskConstMeta(debugName: "Vault_is_unlocked", argNames: ["that"]);

  @override
  Future<void> crateApiVaultVaultLoadFromFile({
    required Vault that,
    required String path,
    required String masterPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_String(masterPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultVaultLoadFromFileConstMeta,
        argValues: [that, path, masterPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultLoadFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "Vault_load_from_file",
        argNames: ["that", "path", "masterPassword"],
      );

  @override
  Future<void> crateApiVaultVaultLock({required Vault that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultLockConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultLockConstMeta =>
      const TaskConstMeta(debugName: "Vault_lock", argNames: ["that"]);

  @override
  Future<Vault> crateApiVaultVaultNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultNewConstMeta =>
      const TaskConstMeta(debugName: "Vault_new", argNames: []);

  @override
  Future<void> crateApiVaultVaultSaveToFile({
    required Vault that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultVaultSaveToFileConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultSaveToFileConstMeta =>
      const TaskConstMeta(
        debugName: "Vault_save_to_file",
        argNames: ["that", "path"],
      );

  @override
  Future<void> crateApiVaultVaultUpdateConnection({
    required Vault that,
    required Connection connection,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
            that,
            serializer,
          );
          sse_encode_box_autoadd_connection(connection, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultVaultUpdateConnectionConstMeta,
        argValues: [that, connection],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultUpdateConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "Vault_update_connection",
        argNames: ["that", "connection"],
      );

  @override
  Future<Connection> crateApiAppAddConnection({
    required String name,
    required Protocol protocol,
    required String host,
    required int port,
    String? username,
    String? password,
    String? privateKeyPath,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_protocol(protocol, serializer);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          sse_encode_opt_String(privateKeyPath, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppAddConnectionConstMeta,
        argValues: [
          name,
          protocol,
          host,
          port,
          username,
          password,
          privateKeyPath,
          path,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppAddConnectionConstMeta => const TaskConstMeta(
    debugName: "add_connection",
    argNames: [
      "name",
      "protocol",
      "host",
      "port",
      "username",
      "password",
      "privateKeyPath",
      "path",
    ],
  );

  @override
  Future<Connection> crateApiModelsConnectionNew({
    required String name,
    required Protocol protocol,
    required String host,
    required int port,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_protocol(protocol, serializer);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connection,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsConnectionNewConstMeta,
        argValues: [name, protocol, host, port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsConnectionNewConstMeta =>
      const TaskConstMeta(
        debugName: "connection_new",
        argNames: ["name", "protocol", "host", "port"],
      );

  @override
  Future<void> crateApiAppCreateVault({
    required String masterPassword,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(masterPassword, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppCreateVaultConstMeta,
        argValues: [masterPassword, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppCreateVaultConstMeta => const TaskConstMeta(
    debugName: "create_vault",
    argNames: ["masterPassword", "path"],
  );

  @override
  String crateApiAppDefaultVaultPath() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppDefaultVaultPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppDefaultVaultPathConstMeta =>
      const TaskConstMeta(debugName: "default_vault_path", argNames: []);

  @override
  Future<void> crateApiAppDeleteConnection({
    required String id,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppDeleteConnectionConstMeta,
        argValues: [id, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppDeleteConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "delete_connection",
        argNames: ["id", "path"],
      );

  @override
  Future<List<Connection>> crateApiAppGetConnections() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_connection,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppGetConnectionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppGetConnectionsConstMeta =>
      const TaskConstMeta(debugName: "get_connections", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiAppIsVaultUnlocked() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppIsVaultUnlockedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppIsVaultUnlockedConstMeta =>
      const TaskConstMeta(debugName: "is_vault_unlocked", argNames: []);

  @override
  void crateApiAppLockVault() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppLockVaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppLockVaultConstMeta =>
      const TaskConstMeta(debugName: "lock_vault", argNames: []);

  @override
  Future<String> crateApiAppTestConnection({required String connectionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppTestConnectionConstMeta,
        argValues: [connectionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppTestConnectionConstMeta => const TaskConstMeta(
    debugName: "test_connection",
    argNames: ["connectionId"],
  );

  @override
  Future<String> crateApiSshTestSshConnection({
    required String host,
    required int port,
    required String username,
    String? password,
    String? privateKeyPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          sse_encode_opt_String(privateKeyPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshTestSshConnectionConstMeta,
        argValues: [host, port, username, password, privateKeyPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshTestSshConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "test_ssh_connection",
        argNames: ["host", "port", "username", "password", "privateKeyPath"],
      );

  @override
  Future<void> crateApiAppUnlockVault({
    required String masterPassword,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(masterPassword, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppUnlockVaultConstMeta,
        argValues: [masterPassword, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppUnlockVaultConstMeta => const TaskConstMeta(
    debugName: "unlock_vault",
    argNames: ["masterPassword", "path"],
  );

  @override
  Future<void> crateApiAppUpdateConnection({
    required Connection connection,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_connection(connection, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAppUpdateConnectionConstMeta,
        argValues: [connection, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppUpdateConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "update_connection",
        argNames: ["connection", "path"],
      );

  @override
  bool crateApiAppVaultExists({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppVaultExistsConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppVaultExistsConstMeta =>
      const TaskConstMeta(debugName: "vault_exists", argNames: ["path"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SshConnection => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SshConnection => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Vault => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Vault => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault;

  @protected
  SshConnection
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SshConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Vault
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SshConnection
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SshConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SshConnection
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SshConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Vault
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SshConnection
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SshConnectionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Vault
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Connection dco_decode_box_autoadd_connection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_connection(raw);
  }

  @protected
  Connection dco_decode_connection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return Connection(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      protocol: dco_decode_protocol(arr[2]),
      host: dco_decode_String(arr[3]),
      port: dco_decode_u_16(arr[4]),
      username: dco_decode_opt_String(arr[5]),
      password: dco_decode_opt_String(arr[6]),
      privateKeyPath: dco_decode_opt_String(arr[7]),
      folder: dco_decode_opt_String(arr[8]),
      tags: dco_decode_list_String(arr[9]),
      notes: dco_decode_opt_String(arr[10]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Connection> dco_decode_list_connection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_connection).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Protocol dco_decode_protocol(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Protocol.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  SshConnection
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SshConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Vault
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SshConnection
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SshConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SshConnection
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SshConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Vault
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SshConnection
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SshConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Vault
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Connection sse_decode_box_autoadd_connection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_connection(deserializer));
  }

  @protected
  Connection sse_decode_connection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_protocol = sse_decode_protocol(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_opt_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    var var_privateKeyPath = sse_decode_opt_String(deserializer);
    var var_folder = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return Connection(
      id: var_id,
      name: var_name,
      protocol: var_protocol,
      host: var_host,
      port: var_port,
      username: var_username,
      password: var_password,
      privateKeyPath: var_privateKeyPath,
      folder: var_folder,
      tags: var_tags,
      notes: var_notes,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Connection> sse_decode_list_connection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Connection>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_connection(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Protocol sse_decode_protocol(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Protocol.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SshConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SshConnectionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
    Vault self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SshConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SshConnectionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SshConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SshConnectionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
    Vault self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SshConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SshConnectionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVault(
    Vault self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VaultImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_connection(
    Connection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_connection(self, serializer);
  }

  @protected
  void sse_encode_connection(Connection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_protocol(self.protocol, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_opt_String(self.username, serializer);
    sse_encode_opt_String(self.password, serializer);
    sse_encode_opt_String(self.privateKeyPath, serializer);
    sse_encode_opt_String(self.folder, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_connection(
    List<Connection> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_connection(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_protocol(Protocol self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class SshConnectionImpl extends RustOpaque implements SshConnection {
  // Not to be used by end users
  SshConnectionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SshConnectionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SshConnection,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SshConnection,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SshConnectionPtr,
  );

  /// Connect to SSH server
  Future<void> connect({required Connection connection}) => RustLib.instance.api
      .crateApiSshSshConnectionConnect(that: this, connection: connection);

  /// Disconnect
  Future<void> disconnect() =>
      RustLib.instance.api.crateApiSshSshConnectionDisconnect(that: this);

  /// Execute a command on the remote server
  Future<String> executeCommand({required String command}) => RustLib
      .instance
      .api
      .crateApiSshSshConnectionExecuteCommand(that: this, command: command);

  /// Test connection
  Future<String> testConnection() =>
      RustLib.instance.api.crateApiSshSshConnectionTestConnection(that: this);
}

@sealed
class VaultImpl extends RustOpaque implements Vault {
  // Not to be used by end users
  VaultImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VaultImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Vault,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Vault,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_VaultPtr,
  );

  /// Add a connection to the in-memory vault.
  Future<void> addConnection({required Connection connection}) => RustLib
      .instance
      .api
      .crateApiVaultVaultAddConnection(that: this, connection: connection);

  /// Create a brand new, empty vault protected by `master_password`.
  /// Does not write to disk - call `save_to_file` afterwards.
  Future<void> create({required String masterPassword}) => RustLib.instance.api
      .crateApiVaultVaultCreate(that: this, masterPassword: masterPassword);

  /// Delete a connection by ID.
  Future<void> deleteConnection({required String id}) => RustLib.instance.api
      .crateApiVaultVaultDeleteConnection(that: this, id: id);

  /// Get a specific connection by ID.
  Future<Connection> getConnection({required String id}) =>
      RustLib.instance.api.crateApiVaultVaultGetConnection(that: this, id: id);

  /// Get all connections.
  Future<List<Connection>> getConnections() =>
      RustLib.instance.api.crateApiVaultVaultGetConnections(that: this);

  /// Check if vault is currently unlocked and usable.
  Future<bool> isUnlocked() =>
      RustLib.instance.api.crateApiVaultVaultIsUnlocked(that: this);

  /// Load and unlock a vault from an encrypted file on disk, verifying
  /// `master_password` against the stored hash before decrypting.
  Future<void> loadFromFile({
    required String path,
    required String masterPassword,
  }) => RustLib.instance.api.crateApiVaultVaultLoadFromFile(
    that: this,
    path: path,
    masterPassword: masterPassword,
  );

  /// Lock the vault, discarding the in-memory decryption key and data.
  Future<void> lock() =>
      RustLib.instance.api.crateApiVaultVaultLock(that: this);

  /// Encrypt and persist the vault to disk.
  Future<void> saveToFile({required String path}) =>
      RustLib.instance.api.crateApiVaultVaultSaveToFile(that: this, path: path);

  /// Update an existing connection.
  Future<void> updateConnection({required Connection connection}) => RustLib
      .instance
      .api
      .crateApiVaultVaultUpdateConnection(that: this, connection: connection);
}
