// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dirs_next_config_dir`, `vault`

/// Default path where the vault file is stored on disk.
/// Callers may also pass a custom path to the save/load functions.
String defaultVaultPath() => RustLib.instance.api.crateApiAppDefaultVaultPath();

/// Create a brand new vault protected by `master_password` and
/// immediately persist it to `path`.
Future<void> createVault({
  required String masterPassword,
  required String path,
}) => RustLib.instance.api.crateApiAppCreateVault(
  masterPassword: masterPassword,
  path: path,
);

/// Unlock (load and decrypt) an existing vault file from `path`.
Future<void> unlockVault({
  required String masterPassword,
  required String path,
}) => RustLib.instance.api.crateApiAppUnlockVault(
  masterPassword: masterPassword,
  path: path,
);

/// Lock the vault, clearing all decrypted data from memory.
void lockVault() => RustLib.instance.api.crateApiAppLockVault();

/// Whether the vault is currently unlocked.
bool isVaultUnlocked() => RustLib.instance.api.crateApiAppIsVaultUnlocked();

/// Whether a vault file already exists at `path`.
bool vaultExists({required String path}) =>
    RustLib.instance.api.crateApiAppVaultExists(path: path);

/// Add a new connection and persist the vault to `path`.
Future<Connection> addConnection({
  required String name,
  required Protocol protocol,
  required String host,
  required int port,
  String? username,
  String? password,
  String? privateKeyPath,
  String? folderId,
  required List<String> tags,
  required String path,
  String? jumpHostId,
}) => RustLib.instance.api.crateApiAppAddConnection(
  name: name,
  protocol: protocol,
  host: host,
  port: port,
  username: username,
  password: password,
  privateKeyPath: privateKeyPath,
  folderId: folderId,
  tags: tags,
  path: path,
  jumpHostId: jumpHostId,
);

/// Retrieve all connections currently stored in the unlocked vault.
Future<List<Connection>> getConnections() =>
    RustLib.instance.api.crateApiAppGetConnections();

/// Retrieve a single connection by ID.
Future<Connection> getConnection({required String id}) =>
    RustLib.instance.api.crateApiAppGetConnection(id: id);

/// Delete a connection by ID and persist the change to `path`.
Future<void> deleteConnection({required String id, required String path}) =>
    RustLib.instance.api.crateApiAppDeleteConnection(id: id, path: path);

/// Update an existing connection and persist the change to `path`.
Future<void> updateConnection({
  required Connection connection,
  required String path,
}) => RustLib.instance.api.crateApiAppUpdateConnection(
  connection: connection,
  path: path,
);

/// Attempt to open an SSH connection using stored credentials for
/// `connection_id`, run a trivial command, then disconnect. Returns
/// a human-readable success message or an error describing what failed.
Future<String> testConnection({required String connectionId}) =>
    RustLib.instance.api.crateApiAppTestConnection(connectionId: connectionId);

/// Add a new folder and persist the vault to `path`.
Future<Folder> addFolder({
  required String name,
  String? parentId,
  required String path,
}) => RustLib.instance.api.crateApiAppAddFolder(
  name: name,
  parentId: parentId,
  path: path,
);

/// Retrieve all folders currently stored in the unlocked vault.
Future<List<Folder>> getFolders() =>
    RustLib.instance.api.crateApiAppGetFolders();

/// Update an existing folder (e.g. rename) and persist the change to `path`.
Future<void> updateFolder({required Folder folder, required String path}) =>
    RustLib.instance.api.crateApiAppUpdateFolder(folder: folder, path: path);

/// Delete a folder by ID and persist the change to `path`.
/// Connections in that folder are moved to the root, not deleted.
Future<void> deleteFolder({required String id, required String path}) =>
    RustLib.instance.api.crateApiAppDeleteFolder(id: id, path: path);

/// Import connections and folders from a mRemoteNG XML file.
/// Returns the number of connections and folders imported.
/// Duplicates (same name+host+port) are skipped.
Future<(BigInt, BigInt)> importMremotengXml({
  required String xmlContent,
  required String path,
}) => RustLib.instance.api.crateApiAppImportMremotengXml(
  xmlContent: xmlContent,
  path: path,
);

/// Export the currently unlocked vault's connections and folders as a
/// plaintext JSON string (contains credentials in cleartext).
Future<String> exportVaultJson() =>
    RustLib.instance.api.crateApiAppExportVaultJson();

/// Open an HTTP/HTTPS URL in the system's default browser.
Future<void> openUrl({required String url}) =>
    RustLib.instance.api.crateApiAppOpenUrl(url: url);
