// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dirs_next_config_dir`, `vault`

/// Default path where the vault file is stored on disk.
/// Callers may also pass a custom path to the save/load functions.
String defaultVaultPath() => RustLib.instance.api.crateApiAppDefaultVaultPath();

/// Create a brand new vault protected by `master_password` and
/// immediately persist it to `path`.
Future<void> createVault({
  required String masterPassword,
  required String path,
}) => RustLib.instance.api.crateApiAppCreateVault(
  masterPassword: masterPassword,
  path: path,
);

/// Unlock (load and decrypt) an existing vault file from `path`.
Future<void> unlockVault({
  required String masterPassword,
  required String path,
}) => RustLib.instance.api.crateApiAppUnlockVault(
  masterPassword: masterPassword,
  path: path,
);

/// Lock the vault, clearing all decrypted data from memory.
void lockVault() => RustLib.instance.api.crateApiAppLockVault();

/// Whether the vault is currently unlocked.
bool isVaultUnlocked() => RustLib.instance.api.crateApiAppIsVaultUnlocked();

/// Whether a vault file already exists at `path`.
bool vaultExists({required String path}) =>
    RustLib.instance.api.crateApiAppVaultExists(path: path);

/// Add a new connection and persist the vault to `path`.
Future<Connection> addConnection({
  required String name,
  required Protocol protocol,
  required String host,
  required int port,
  String? username,
  String? password,
  String? privateKeyPath,
  required String path,
}) => RustLib.instance.api.crateApiAppAddConnection(
  name: name,
  protocol: protocol,
  host: host,
  port: port,
  username: username,
  password: password,
  privateKeyPath: privateKeyPath,
  path: path,
);

/// Retrieve all connections currently stored in the unlocked vault.
Future<List<Connection>> getConnections() =>
    RustLib.instance.api.crateApiAppGetConnections();

/// Delete a connection by ID and persist the change to `path`.
Future<void> deleteConnection({required String id, required String path}) =>
    RustLib.instance.api.crateApiAppDeleteConnection(id: id, path: path);

/// Update an existing connection and persist the change to `path`.
Future<void> updateConnection({
  required Connection connection,
  required String path,
}) => RustLib.instance.api.crateApiAppUpdateConnection(
  connection: connection,
  path: path,
);

/// Attempt to open an SSH connection using stored credentials for
/// `connection_id`, run a trivial command, then disconnect. Returns
/// a human-readable success message or an error describing what failed.
Future<String> testConnection({required String connectionId}) =>
    RustLib.instance.api.crateApiAppTestConnection(connectionId: connectionId);
