// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_nodes`

/// Parse a mRemoteNG XML file and extract connections and folders.
/// Returns (connections, folders).
Future<(List<Connection>, List<Folder>)> parseMremotengXml({
  required String xmlContent,
}) => RustLib.instance.api.crateApiImportParseMremotengXml(
  xmlContent: xmlContent,
);
