// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

class Connection {
  final String id;
  final String name;
  final Protocol protocol;
  final String host;
  final int port;
  final String? username;
  final String? password;
  final String? privateKeyPath;
  final String? folderId;
  final List<String> tags;
  final String? notes;
  final String? jumpHostId;

  const Connection({
    required this.id,
    required this.name,
    required this.protocol,
    required this.host,
    required this.port,
    this.username,
    this.password,
    this.privateKeyPath,
    this.folderId,
    required this.tags,
    this.notes,
    this.jumpHostId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Connection> newInstance({
    required String name,
    required Protocol protocol,
    required String host,
    required int port,
  }) => RustLib.instance.api.crateApiModelsConnectionNew(
    name: name,
    protocol: protocol,
    host: host,
    port: port,
  );

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      protocol.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      privateKeyPath.hashCode ^
      folderId.hashCode ^
      tags.hashCode ^
      notes.hashCode ^
      jumpHostId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Connection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          protocol == other.protocol &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          privateKeyPath == other.privateKeyPath &&
          folderId == other.folderId &&
          tags == other.tags &&
          notes == other.notes &&
          jumpHostId == other.jumpHostId;
}

class Folder {
  final String id;
  final String name;
  final String? parentId;

  const Folder({required this.id, required this.name, this.parentId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Folder> newInstance({required String name, String? parentId}) =>
      RustLib.instance.api.crateApiModelsFolderNew(
        name: name,
        parentId: parentId,
      );

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ parentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Folder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId;
}

enum Protocol { ssh, rdp, vnc, http, https, vpn }
