// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectionFolder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

class Connection {
  final String id;
  final String name;
  final Protocol protocol;
  final String host;
  final int port;
  final String? username;
  final String? password;
  final String? privateKeyPath;
  final String? folder;
  final List<String> tags;
  final String? notes;

  const Connection({
    required this.id,
    required this.name,
    required this.protocol,
    required this.host,
    required this.port,
    this.username,
    this.password,
    this.privateKeyPath,
    this.folder,
    required this.tags,
    this.notes,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Connection> newInstance({
    required String name,
    required Protocol protocol,
    required String host,
    required int port,
  }) => RustLib.instance.api.crateApiModelsConnectionNew(
    name: name,
    protocol: protocol,
    host: host,
    port: port,
  );

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      protocol.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      privateKeyPath.hashCode ^
      folder.hashCode ^
      tags.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Connection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          protocol == other.protocol &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          privateKeyPath == other.privateKeyPath &&
          folder == other.folder &&
          tags == other.tags &&
          notes == other.notes;
}

enum Protocol { ssh, rdp, vnc, http, https, vpn }
