// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_rdp_config`, `connect_rdp`, `extract_tls_server_public_key`, `tls_upgrade`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RdpState`

/// Test RDP connection with credentials
Future<String> testRdpConnection({
  required String host,
  required int port,
  required String username,
  required String password,
  String? domain,
}) => RustLib.instance.api.crateApiRdpTestRdpConnection(
  host: host,
  port: port,
  username: username,
  password: password,
  domain: domain,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RdpConnection>>
abstract class RdpConnection implements RustOpaqueInterface {
  Future<void> connect({required Connection connection});

  Future<void> disconnect();

  Future<Uint8List> getFramebuffer();

  Future<(int, int)> getSize();

  Future<bool> isConnected();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RdpConnection> newInstance() =>
      RustLib.instance.api.crateApiRdpRdpConnectionNew();
}
