// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `authenticate`, `connect_with_timeout`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Test SSH connection (standalone function for FFI), optionally tunneled
/// through a jump host.
Future<String> testSshConnection({
  required String host,
  required int port,
  required String username,
  String? password,
  String? privateKeyPath,
  String? privateKeyPassphrase,
}) => RustLib.instance.api.crateApiSshTestSshConnection(
  host: host,
  port: port,
  username: username,
  password: password,
  privateKeyPath: privateKeyPath,
  privateKeyPassphrase: privateKeyPassphrase,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshConnection>>
abstract class SshConnection implements RustOpaqueInterface {
  /// Close the interactive shell.
  Future<void> closeShell();

  /// Connect directly to `connection`'s host:port and authenticate.
  /// If `connection.jump_host_id` is set, automatically routes through
  /// `connect_via_jump_host` instead.
  Future<void> connect({required Connection connection});

  /// Connect to `connection`'s host:port by first establishing an SSH
  /// session to `jump_host`, then using SSH port forwarding to tunnel
  /// a local connection through it. This is the standard "jump host" /
  /// "bastion host" pattern.
  ///
  /// Implementation: We create a local TCP proxy that bridges between
  /// a loopback TcpStream (which satisfies Session::set_tcp_stream's
  /// AsRawSocket requirement) and the SSH channel opened via
  /// channel_direct_tcpip on the jump host.
  Future<void> connectViaJumpHost({
    required Connection connection,
    required Connection jumpHost,
  });

  /// Disconnect
  Future<void> disconnect();

  /// Execute a command on the remote server
  Future<String> executeCommand({required String command});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SshConnection> newInstance() =>
      RustLib.instance.api.crateApiSshSshConnectionNew();

  /// Open an interactive shell (PTY) and start streaming output to Flutter.
  /// This spawns a background thread that continuously reads from the channel
  /// and sends data chunks via the `output_sink`.
  ///
  /// Call `send_input` to write data to the shell, and `resize_pty` to update
  /// terminal dimensions.
  Stream<Uint8List> openShell({
    required String termType,
    required int cols,
    required int rows,
  });

  /// Resize the PTY when terminal window size changes.
  Future<void> resizePty({required int cols, required int rows});

  /// Send input (keystrokes) to the interactive shell.
  Future<void> sendInput({required List<int> data});

  /// Test connection
  Future<String> testConnection();
}
