// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Test SSH connection (standalone function for FFI)
Future<String> testSshConnection({
  required String host,
  required int port,
  required String username,
  String? password,
  String? privateKeyPath,
}) => RustLib.instance.api.crateApiSshTestSshConnection(
  host: host,
  port: port,
  username: username,
  password: password,
  privateKeyPath: privateKeyPath,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshConnection>>
abstract class SshConnection implements RustOpaqueInterface {
  /// Connect to SSH server
  Future<void> connect({required Connection connection});

  /// Disconnect
  Future<void> disconnect();

  /// Execute a command on the remote server
  Future<String> executeCommand({required String command});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SshConnection> newInstance() =>
      RustLib.instance.api.crateApiSshSshConnectionNew();

  /// Test connection
  Future<String> testConnection();
}
