// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Test VNC connection (not yet implemented)
Future<String> testVncConnection({
  required String host,
  required int port,
  String? password,
}) => RustLib.instance.api.crateApiVncTestVncConnection(
  host: host,
  port: port,
  password: password,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VncConnection>>
abstract class VncConnection implements RustOpaqueInterface {
  Future<void> connect({required Connection connection});

  Future<void> disconnect();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<VncConnection> newInstance() =>
      RustLib.instance.api.crateApiVncVncConnectionNew();
}
